### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Bakumon** [kitian616/jekyll-TeXt-theme#10]
建议加入基于 LeanCloud 的评论系统。

https://valine.js.org/

**Comment by kitian616** [comment]
这个 6，放到下一个功能版本。

**Comment by Bakumon** [comment]
🙏我不是前端，只能提个功能了

**Comment by WangQiru** [comment]
这个 https://gitalk.github.io/ 基于githun issues，更6。[我的站](https://wangqiru.com/)已经用上了。
前端可能会有点小问题，基主调试下？ https://github.com/kitian616/jekyll-TeXt-theme/pull/20 。

**Comment by kitian616** [comment]
@WangQiru 晚上吧，多谢你的 pr。

gitalk 是个好东西，不过个人还是更倾向于专业的评论系统，毕竟 Issue 可不是为了单纯的评论而存在的。不过多一个选择也是很好的。

**Comment by kitian616** [comment]
gitalk support has added to the main branch, Demo is [HERE](https://tianqi.name/jekyll-TeXt-theme/test/2017/10/12/english.html). @WangQiru

**Comment by kitian616** [comment]
we already have gitalk, no need to add valine.
