### ISSUE TITLE
layout 'home' doesn't work correctly

### ISSUE THREAD

**Issue by zhoudaxia233** [kitian616/jekyll-TeXt-theme#103]
### Hello, I built a blog folder and created an index.html as below:
<img src="https://user-images.githubusercontent.com/30392089/46046929-314dd280-c123-11e8-98fc-ecf03a763d3a.png" width="30%">

### And use "home" as layout:
<img src="https://user-images.githubusercontent.com/30392089/46047012-825dc680-c123-11e8-8d16-b3d1f67640ca.png" width="30%">

### However, when I try to access http://127.0.0.1:4000/blog/, I can see nothing but a blank page like this:
(seems like only the content part doesn't work)
(I've already set up all necessary home paths in yml file)
<img src="https://user-images.githubusercontent.com/30392089/46047145-1334a200-c124-11e8-938d-59e9b381d430.png" width="60%">

### I have another index.html which is exactly the same content as the one in blog folder but locates in the root directory:
<img src="https://user-images.githubusercontent.com/30392089/46047726-7de6dd00-c126-11e8-8abd-102ed0b825aa.png" width="30%">

### And it works just fine:
<img src="https://user-images.githubusercontent.com/30392089/46047966-6f4cf580-c127-11e8-8400-a3a39312e0a2.png" width="60%">

**Comment by kitian616** [comment]
you need also change paginate_path  to blog path. refer to https://github.com/kitian616/jekyll-TeXt-theme/blob/master/docs/_config.yml#L99.

在 2018年9月26日，07:01，Zheng Zhou <notifications@github.com<mailto:notifications@github.com>> 写道：

Hello, I built a blog folder and created an index.html as below:

[https://user-images.githubusercontent.com/30392089/46046929-314dd280-c123-11e8-98fc-ecf03a763d3a.png]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F30392089%2F46046929-314dd280-c123-11e8-98fc-ecf03a763d3a.png&data=02%7C01%7C%7C568d05acd8a3437ac48b08d6233ac3fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636735132630212526&sdata=x7IhS0tUed%2BtbIc4yEbkpKv75%2FlTxmA79KNkeQfU3vc%3D&reserved=0>

And use "home" as layout:

[https://user-images.githubusercontent.com/30392089/46047012-825dc680-c123-11e8-8d16-b3d1f67640ca.png]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F30392089%2F46047012-825dc680-c123-11e8-8d16-b3d1f67640ca.png&data=02%7C01%7C%7C568d05acd8a3437ac48b08d6233ac3fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636735132630368773&sdata=eEVToSUol9aqaXXvPDBQqo6QA2DEXyFc2uoXYDfcrnQ%3D&reserved=0>

However, when I try to access http://127.0.0.1:4000/blog/<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2F127.0.0.1%3A4000%2Fblog%2F&data=02%7C01%7C%7C568d05acd8a3437ac48b08d6233ac3fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636735132630368773&sdata=yRizJY4J%2FJKUHtU555fqTbn3PY9sUF%2BRNE8MFDPKwjc%3D&reserved=0>, I can see nothing but a blank page like this:

(seems like only the content part doesn't work)
(I've already set up all necessary home paths in yml file)
[https://user-images.githubusercontent.com/30392089/46047145-1334a200-c124-11e8-938d-59e9b381d430.png]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F30392089%2F46047145-1334a200-c124-11e8-938d-59e9b381d430.png&data=02%7C01%7C%7C568d05acd8a3437ac48b08d6233ac3fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636735132630368773&sdata=Jv08u%2Fz5QZA3qV1tUPlxhsuiOsUB2kWitf5NqD3h%2F3s%3D&reserved=0>

I have another index.html which is exactly the same content as the one in blog folder but locates in the root directory:

[https://user-images.githubusercontent.com/30392089/46047726-7de6dd00-c126-11e8-8abd-102ed0b825aa.png]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F30392089%2F46047726-7de6dd00-c126-11e8-8abd-102ed0b825aa.png&data=02%7C01%7C%7C568d05acd8a3437ac48b08d6233ac3fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636735132630368773&sdata=Z3N%2F7BakJKJYUJ2R%2B%2BjYAbachTtk%2FhtVmrvxK8%2FK5CE%3D&reserved=0>

And it works just fine:

[https://user-images.githubusercontent.com/30392089/46047966-6f4cf580-c127-11e8-8400-a3a39312e0a2.png]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F30392089%2F46047966-6f4cf580-c127-11e8-8400-a3a39312e0a2.png&data=02%7C01%7C%7C568d05acd8a3437ac48b08d6233ac3fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636735132630368773&sdata=ZZG89NvkPPjo4TKYeAR%2FuPidn8DCEBRMT01uR7op3Lw%3D&reserved=0>

I'd like to know why it won't work if I put the index.html in blog folder? What changes shall I apply to make it work correctly?
Thanks in advance!

**Comment by zhoudaxia233** [comment]
@kitian616 Thanks a lot, now it works!

**Comment by Harrypotterrrr** [comment]
@kitian616 Hi, If I have two directories which contains two collections of posts (eg. posts, and talks) how to use jekyll paginator to deal with this case?
