### ISSUE TITLE
toc: false doesn't turn off table of contents

### ISSUE THREAD

**Issue by sammosummo** [kitian616/jekyll-TeXt-theme#109]
I have set `toc: false` in both `config.yaml` and on individual posts, yet the table of contents still appears. Any idea why?

Example:
https://sammosummo.github.io/2018/07/03/about.html

**Comment by kitian616** [comment]
![image](https://user-images.githubusercontent.com/9103558/48303731-f5db5c00-e548-11e8-949f-e021f83dd13d.png)

Wrong Indentation, the Front Matter won't work.
