### ISSUE TITLE
关于标题旁的svg图标无法在apple移动端显示的问题

### ISSUE THREAD

**Issue by Paradox4869** [kitian616/jekyll-TeXt-theme#111]
![50003988-dfb0-4fae-8823-216dae5d33b9](https://user-images.githubusercontent.com/25121041/47520344-8451ab80-d8c2-11e8-8079-f3119ae4e7da.jpeg)
打扰问一下：如图 我应该修改哪一个文件？谢谢

**Comment by Paradox4869** [comment]
> What do you mean by "apple 移动端显示的问题"，some browser didn't show the logo?

yeah, the first picture is displayed on my iPad's chrome, and the icon disapears. It's the same on mobile phone whether it's chrome or safari.
![inkedinkedimg_0312_li](https://user-images.githubusercontent.com/25121041/48303920-f9241700-e54b-11e8-8b40-240dd7e376d9.jpg)
the second one is on my PC's chrome.
![inked111_li](https://user-images.githubusercontent.com/25121041/48304016-5ff60000-e54d-11e8-8e94-bafdf47675d5.jpg)
Thanks for your reply. I hope I have descriped my problem clearly.

**Comment by kitian616** [comment]
Your logo have some compatibility problem.

You can remove the outer `<svg>` tag, since it exactly  a png image.

May I need rename `logo.svg` to `logo.html`.
