### ISSUE TITLE
图表没能正确填充

### ISSUE THREAD

**Issue by wenmm** [kitian616/jekyll-TeXt-theme#114]
您好！我现在有个小困扰就是我用jupyter pandas生成了图表然后下载成md格式，在博客上会有显示不全。
![13](https://user-images.githubusercontent.com/31941752/48119005-ff469900-e2a8-11e8-9797-76b647d39861.PNG)

**Comment by kitian616** [comment]
Code? @wenmm

**Comment by wenmm** [comment]
您好！ipynb地址如下：https://github.com/wenmm/wenmm.github.io/blob/master/test/2018-10-27-pandasnote.ipynb，然后此文件下载为.md文件如下：https://github.com/wenmm/wenmm.github.io/blob/master/test/2018-10-27-pandasnote.md，麻烦您了。
