### ISSUE TITLE
Can't Use on Github Pages.

### ISSUE THREAD

**Issue by Atlas3621** [kitian616/jekyll-TeXt-theme#122]
I am trying to use this theme on github pages, but I get this error.

Your SCSS file `assets/css/main.scss` has an error on line 6: File to import not found or unreadable: skins/. Load path: /hoosegow/.bundle/ruby/2.5.0/gems/jekyll-theme-primer-0.5.3/_sass. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss/.

Any Ideas?

**Comment by Atlas3621** [comment]
Tried Remote Theme,

 Your site is having problems building: Your SCSS file assets/css/main.scss has an error on line 6: File to import not found or unreadable: skins/. Load paths: /tmp/jekyll-remote-theme-20181205-7-fw8h4w/_sass /hoosegow/.bundle/ruby/2.5.0/gems/jekyll-theme-primer-0.5.3/_sass /tmp/jekyll-remote-theme-20181205-7-1bhjolw/_sass. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss/.

Got that Error.

**Comment by Atlas3621** [comment]
Tried referrign to that example, even straight up copying it. Just shows blank page.

**Comment by Atlas3621** [comment]
Tried that, css isn't working.

**Comment by kitian616** [comment]
This is the example I mentioned above: 

```yml
theme: jekyll-text-theme
```
And this is your change:

```yml
remote-theme: jekyll-text-theme`
```

Before you change something, refer to the [documentation](https://github.com/benbalter/jekyll-remote-theme), don't always guessing.
