### ISSUE TITLE
Setting `toc: false` doesn't align text and header for regular articles

### ISSUE THREAD

**Issue by sammosummo** [kitian616/jekyll-TeXt-theme#125]
Articles have exactly the same layout when `toc: false` and `toc: true`. The only difference is that the TOC is gone in the former case. This means that the main text is off-center and that the header is not right-aligned with the text.

**Comment by kitian616** [comment]
Could you get a screenshot of this page?

**Comment by sammosummo** [comment]
![screen shot 2018-12-28 at 4 53 08 pm](https://user-images.githubusercontent.com/9464950/50529195-396e3300-0ac1-11e9-858c-1e898d96dfa6.png)

**Comment by sammosummo** [comment]
![screen shot 2018-12-28 at 4 55 07 pm](https://user-images.githubusercontent.com/9464950/50529219-64f11d80-0ac1-11e9-9aaf-64e05c7eed3f.png)
