### ISSUE TITLE
Keep header link highlighted when navigating through other pages

### ISSUE THREAD

**Issue by ojw28** [kitian616/jekyll-TeXt-theme#127]
Often, websites are structured to have a few top level "areas" displayed horizontally in the header, and within each area a number of pages. The TeXt demo app is an example. Is there a way to configure TeXt so that the top level "area" link remains highlighted whenever you're on any page within that area, rather than just when you're on the landing page that the link directly points to?

Example:
The "Docs" link in the header is highlighted on this page:
https://tianqi.name/jekyll-TeXt-theme/docs/en/quick-start
But not on this page, or any other page within the documentation area:
https://tianqi.name/jekyll-TeXt-theme/docs/en/structure

It would be good if it were possible to configure things so that the "Docs" link in the header remained highlighted on all of these pages. Is it possible, and if not, could this be considered as a feature request?

**Comment by kitian616** [comment]
This is possible by using a certain key to tell TeXt which "area" the current page in.

**Comment by ojw28** [comment]
Is this a feature request, or are you saying this is already possible? Thanks!

**Comment by kitian616** [comment]
A feature request.
