### ISSUE TITLE
Feature request: Google Custom Search support

### ISSUE THREAD

**Issue by ojw28** [kitian616/jekyll-TeXt-theme#128]
Would it be possible to support [Google Custom Search](https://www.google.com/cse)? The current search functionality seems to only support searching page titles, where-as Google Custom Search will be far more useful for searching the actual page content.

Aside: What's the easiest way to disable the existing search functionality in TeXt? I figured out a few ways, but none were as simple as adding a line to _config.yml, which I'm hoping is possible!

**Comment by kitian616** [comment]
This can be a choice for search. In fact, as Google Custom Search need jump out to get the results, there is another search tool calls [Algolia](https://www.algolia.com/) which I'm more likely to support.

The easiest way is to remove the search code.

**Comment by kitian616** [comment]
#95

**Comment by ojw28** [comment]
> Google Custom Search need jump out to get the results

I don't think this is correct. It's actually pretty flexible with where you're allowed to display the results. It's also quite flexible in allowing you to place the search box and search results separately (e.g. to put the search box in a header, and have it load a results page). You can also use only the results part, which I think lets you use it in conjunction with your own search box.

**Comment by kitian616** [comment]
![image](https://user-images.githubusercontent.com/9103558/50476132-eda88480-0a01-11e9-90ab-e5dcf6045266.png)
I mean this，from the introducing video.

**Comment by ojw28** [comment]
A pop-up definitely isn't required (I'm not sure if it ever was, but either way that video is 6 years old now :)). See for example some of the demos [here](https://developers.google.com/custom-search/docs/tutorial/implementingsearchbox).

**Comment by ojw28** [comment]
A few real world examples that are using Google Custom Search:
https://www.princeton.edu
https://developer.chrome.com

**Comment by ojw28** [comment]
Wohoo; it's great that you're looking at this!

I gave it a go by cloning the repository, changing the default provider in `_config.yml`, and filling in my custom search engine id. For me it resulted in the page fading but nothing appearing in which to search. Is there a further step I need to do?

I also tried setting to false and observed the search icon was still present, which I think is due to the comment I've posted [here](https://github.com/kitian616/jekyll-TeXt-theme/commit/7b6d157e12703f2f9d29970ef2fb2a6ef9c246ad#r31858883).

**Comment by kitian616** [comment]
Weird, sometime Jekyll parse `gcse:xxx` to `xxx`.

**Comment by ojw28** [comment]
Thanks for your work :).

**Comment by kitian616** [comment]
Did all the pages didn't show search elements?

I found if the page have emoji code like `:star:` Jekyll will render `gcse:xxxx` to `xxxx`, and so Custom Search didn't render.

**Comment by ojw28** [comment]
Interesting :). It works for me on a page without any emojis.

Although clicking on the dark bit outside of the search results, after getting search results, doesn't let you get back to the original page. You have to press the "X" in the search box to get back. It feels like clicking outside the area should take you back.

**Comment by kitian616** [comment]
It is a bug, but have workaround.

Click and go back, more reasonable I think. Thanks for you advice.
