### ISSUE TITLE
评论模块忽然失效

### ISSUE THREAD

**Issue by smartadpole** [kitian616/jekyll-TeXt-theme#129]
## Description

[Description of the bug, feature or question]
## 评论功能无法正常使用
- 评论去功能之前测试过能正常使用；  
- 在一次提交后，评论功能无法自动创建issue，导致评论功能不能用；  
- 同时，已有评论也不出现 comment 按钮；  
    - 一直停留在登录界面，我点登录，直接跳到我 github，并未执行登录操作，像死循环；  
![image](https://user-images.githubusercontent.com/23243371/50476028-7bd03b00-0a01-11e9-88d4-5e79cfd06d6b.png)

## 进展1：评论区可正常登录
上述评论区登录异常的情况回复，原因是如下配置不对;  
原来的配置：  
![image](https://user-images.githubusercontent.com/23243371/50476502-5ba17b80-0a03-11e9-9ca0-fe00cd2d7562.png)

新配置：  
![image](https://user-images.githubusercontent.com/23243371/50476476-462c5180-0a03-11e9-8bc6-13c541f59308.png)

但是，以前没有创建成功的issue依然没有出来；同时新增文章也不能自动创建 issue；

## 进展2：部分评论区可正常评论  
事实：评论区只要是正常显示，就可以进行评论，而不是之前一直理解的，只要发布，就会自动创建相应的 issue；是先有人评论了，才会开 issue；  

问题：部分博文仍不可评论  
![image](https://user-images.githubusercontent.com/23243371/50477092-d2d80f00-0a05-11e9-914b-0f142da05ce2.png)
只有一篇[博文](https://smartadpole.github.io/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BB/%E8%AE%AD%E7%BB%83%E4%BC%98%E5%8C%96/2018/12/27/%E5%88%86%E7%B1%BB%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83%E6%8A%80%E5%B7%A7.html)是这样，是什么问题？

## 进展3：该[博文](https://smartadpole.github.io/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BB/%E8%AE%AD%E7%BB%83%E4%BC%98%E5%8C%96/2018/12/27/%E5%88%86%E7%B1%BB%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83%E6%8A%80%E5%B7%A7.html)也可以正常评论了  
原来的 key： image-classification-train-trickers-review-20181227 
修改后的 key：  image_c-train-trickers-review-20181227   
在我看来，他们只有长度的变化；  

博客地址<https://github.com/smartadpole/smartadpole.github.io>
## Environment (If Necessary)

- OS:ubuntu 16.04
- Jekyll: jekyll 3.8.5
- Broser:  Chrome

**Comment by kitian616** [comment]
This is not a TeXt issue, you can refer to [gitalk](https://github.com/gitalk/gitalk) to find something.

**Comment by smartadpole** [comment]
> This is not a TeXt issue, you can refer to [gitalk](https://github.com/gitalk/gitalk) to find something.

Thankyou! The problem is solved.
对于用户来说，分不清这个问题是属于 TeXt  还是 gtalk；最终发现只是配置的问题；
## 建议
我们可以把这些操作步骤添加到使用文档里；
