### ISSUE TITLE
Header logo + title alignment issue

### ISSUE THREAD

**Issue by ojw28** [kitian616/jekyll-TeXt-theme#131]
## Description

When using a custom logo and my own title "ExoPlayer", I'm seeing that the logo and title are not nicely aligned (and I'm fairly confident this is not due to an alignment issue within the logo asset):

![align](https://user-images.githubusercontent.com/7881572/50604191-fdb6dd00-0eb5-11e9-849a-0ec9fc211cf9.png)

Here's the logo I'm using, if you want to reproduce:

[logo.svg.zip](https://github.com/kitian616/jekyll-TeXt-theme/files/2721428/logo.svg.zip)

**Expected behavior:**

Nicer alignment between logo and title. I'd expect the "point" of the triangle to align roughly with the middle of the E vertically. So the text seems too high relative to the logo, although I'm not sure which one should be adjusted because I assume there's also a preferred alignment with the stuff on the right hand side.

**Comment by kitian616** [comment]
Is your HEAD behind [this commit](https://github.com/kitian616/jekyll-TeXt-theme/commit/35a0a90e62b3cbefb4eb6a7b648c951a629d977e#diff-e2bbf4b7fadfd97d1a887e8be6d175ee)?

**Comment by ojw28** [comment]
I would have been behind that, yes. Looks great in the screenshot above! Closing assumed fixed; thanks!
