### ISSUE TITLE
How do I make my logo bigger?

### ISSUE THREAD

**Issue by wrongsyntax** [kitian616/jekyll-TeXt-theme#135]
My logo looks too small in the header, how can I make it appear bigger? The site is at https://wrongsyntax.github.io

**Comment by wrongsyntax** [comment]
I found out how to do it.

Here are the steps for future reference:

1. Navigate to `/_sass/components/_header.scss`
2. Find lines 64 and 65
3. Change the `* 1.6` to whatever you want

**Comment by ruisonghan** [comment]
wow, thanks, I faced the same problem at first.

**Comment by kitian616** [comment]
I'll make it configurable.

**Comment by ruisonghan** [comment]
> I'll make it configurable.

Thanks a lot.  Just wanted to use your template to build a tech blog and my background is not software engineering so it would be lovely if there is a more detailed guide.
