### ISSUE TITLE
Bug: distorted avatar photo

### ISSUE THREAD

**Issue by ziofil** [kitian616/jekyll-TeXt-theme#143]
**Description**

The avatar that is displayed in the author info box below a post is distorted. It's rounded only on the bottom and there is no separation from the author's name.

**Steps to Reproduce**

1. set avatar path in authors.yml to some photo
2. use `show_author_profile: true` in the front matter of a post
3. look at result

**Expected behavior**
A cropped version of the photo, in the shape of a circle.

**Screenshots (If Necessary)**

<img width="706" alt="capture d ecran 2019-01-26 a 18 27 20" src="https://user-images.githubusercontent.com/8944955/51790622-1bffb800-2198-11e9-9c7c-6c7e98c9ed0e.png">

<img width="485" alt="capture d ecran 2019-01-26 a 18 28 59" src="https://user-images.githubusercontent.com/8944955/51790639-4b162980-2198-11e9-8990-959b387cd506.png">

**Environment (If Necessary)**

- OS: macOS 10.14.2
- Ruby: 2.5.1
- Jekyll: 3.8.5
- Browser: Safari, Firefox

**Comment by kitian616** [comment]
I can't reappear it, what's the size of your photo?

[THIS](https://tianqi.name/jekyll-TeXt-theme/post/2017/04/15/author.html) is the test demo I use, could you tell me the different between your page and the demo?

**Comment by ziofil** [comment]
If I use a smaller size it works correctly. Perhaps it was that the photo that I was using was rectangular and large. Perhaps you could add a small comment in the demo page, to remind users to use square images?
