### ISSUE TITLE
Bug:dark主题，gitalk输入框的文字也会变成白色，导致无法看清输入内容。

### ISSUE THREAD

**Issue by Mutuduxf** [kitian616/jekyll-TeXt-theme#144]
gitalk输入字体的颜色为rgba(255,255,255,0.7)，输入框背景色为#fbfbfb，导致无法看清输入内容。

**Comment by kitian616** [comment]
Make a pull request to [gitalk](https://github.com/gitalk/gitalk/pulls).

**Comment by ruisonghan** [comment]
@kitian616 When I used the Google custom search engine under the dark theme, I faced the same problem. I could see the keywords that I typed. 

By the way, I used the custom search engine to search some words in my blog but I didn't succeed, do I need to wait for a few days until Google has recorded my GitHub pages? Now I have switched back the default search engine. Thanks.

**Comment by yuxiaoyuan0406** [comment]
这个问题貌似没有完全解决，dark主题下gitalk评论的标题仍然是白色文字，如下图所示
![image](https://user-images.githubusercontent.com/35896236/187609040-0f0c2963-4a87-4da7-8823-863b5da4ab2e.png)
选中之后可以看到文字是存在的
![image](https://user-images.githubusercontent.com/35896236/187609160-10064479-2c71-41b5-9aca-cf9bb4aa4119.png)
