### ISSUE TITLE
圖片過大時，會造成文章跑版無法顯示

### ISSUE THREAD

**Issue by RickJiangOnGitHub** [kitian616/jekyll-TeXt-theme#15]
![](https://i.imgur.com/kGH4lIQ.jpg)

如我插入這張圖時，在主頁面（index)時，將會造成整個畫面走版，僅剩Click to read more ...
點入後，整個文章頁面將會異位，這部分應該如何修正？還是只能自行縮小圖片再上傳插入呢？
謝謝

**Comment by kitian616** [comment]
`https://github.com/kitian616/jekyll-TeXt-theme/blob/master/test/_posts/2016-12-22-images.md` 示例（[访问](https://tianqi.name/jekyll-TeXt-theme/test/2016/12/22/images.html)）里的图片都是比较大的图片，并没有引起什么问题，你是怎么插入在哪插入这张图片的？麻烦提供更详细的信息。

**Comment by RickJiangOnGitHub** [comment]
我的插入tag操作失誤，謝謝幫助
