### ISSUE TITLE
Bug: Started Error

### ISSUE THREAD

**Issue by str818** [kitian616/jekyll-TeXt-theme#166]
Every interface will report errors. Today, we just had this error. Can't we get JS static resources?
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure script '<URL>'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by kitian616** [comment]
If your page's url is https, all the resource used by the page must also https. You can:

1. Change page url to http
2. Change resource url to https

**Comment by str818** [comment]
Thanks, only the Chrome browser reported an error yesterday, but it was automatically restored last night.

Finally, thanks to the open source TeXt theme, I really like its style.
