### ISSUE TITLE
无端生成 pages文件夹

### ISSUE THREAD

**Issue by smartadpole** [kitian616/jekyll-TeXt-theme#169]
**Description**

[Description of the bug]

最开始预览网站时，生成的文件都正常，按照标签或时间来生成；不知什么时候，发现异常：   
![image](https://user-images.githubusercontent.com/23243371/56349455-29f33100-61fb-11e9-8953-0c0319351385.png)
其中 page 开头的都不是我给的标签，求解答；

[Blog](https://github.com/smartadpole/smartadpole.github.io)

**Comment by kitian616** [comment]
These is for the  pagination, but seems too much. Is your site OK now?

![image](https://user-images.githubusercontent.com/9103558/57129661-ab38ef00-6dc9-11e9-95da-0d6261f21fd0.png)
