### ISSUE TITLE
https://tianqi.name/jekyll-TeXt-theme/ is 404 on mobile Phone

### ISSUE THREAD

**Issue by jinjiankla** [kitian616/jekyll-TeXt-theme#18]
my blog has the same problem.(The Home page)

**Comment by kitian616** [comment]
The demo page is visible on my iPhone. But I can’t open your site.
Is your site always not visible or just broke after a certain commit ?

**Comment by WangQiru** [comment]
@jinjiankla mind providing the site url here? Can't reproduce the error on my side.

**Comment by kitian616** [comment]
http://jinjian.info/, seems OK now

**Comment by kitian616** [comment]
Not active for some time, closed.
