### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by avently** [kitian616/jekyll-TeXt-theme#184]
## Description
Hello. Found your beautiful theme. Thank you for your work!
Git repository is licenced under MIT license. But here I see some other licences: 
https://github.com/kitian616/jekyll-TeXt-theme/blob/master/docs/_data/licenses.yml

Why is that here? Is it just for documentaion for the theme? Can I use the theme for my commercial projects?

**Comment by kitian616** [comment]
CC is for articles, MIT is for the Theme.
You can use the theme for commercial projects.
