### ISSUE TITLE
Feature request: GFM with Tomorrow theme has differrent outlook from Liquid tags syntax?

### ISSUE THREAD

**Issue by micfan** [kitian616/jekyll-TeXt-theme#192]
## Description

I mean how to let the  “Github Flavored Markdown” has the same look of Liquid Syntax highlight code blocks?

eg. thie render result is differrent between ``` from {% highlight %}

**Comment by kitian616** [comment]
you want ```  same to  {% highlight %} ?

**Comment by micfan** [comment]
yes

**Comment by micfan** [comment]
I close this issue, may be no one need ```, thank your beautiful theme!

**Comment by kitian616** [comment]
You can use ```, almost same to {% highlight %}.

\`\`\` ⬇️

![image](https://user-images.githubusercontent.com/9103558/61881291-f544f300-af28-11e9-8202-3dc1f5444fa1.png)

{% highlight %} ⬇️

![image](https://user-images.githubusercontent.com/9103558/61881266-eb22f480-af28-11e9-9ba2-5ff124b8932a.png)

**Comment by micfan** [comment]
emm, maybe there was some bad config in my local `_config.yml`...
