### ISSUE TITLE
Google Analytics 似乎有点问题

### ISSUE THREAD

**Issue by iseesaw** [kitian616/jekyll-TeXt-theme#209]
配置了Google Analytics 的 tracking-id，但是网站上没有显示相关统计数据？？

**Comment by leiyuwork** [comment]
我也碰到了类似问题，请问你解决了吗

**Comment by iseesaw** [comment]
> 我也碰到了类似问题，请问你解决了吗

这个好像只能在 Google Analytics 网站上能看到统计信息，没法显示在网站上。。。
最后也没解决，换成 Hexo 的 Next 主题了，还不错

**Comment by leiyuwork** [comment]
我现在google analytics网站里数据也是0...
