### ISSUE TITLE
Navlist 中的 url 不能添加绝对路径

### ISSUE THREAD

**Issue by Sd-Invol** [kitian616/jekyll-TeXt-theme#21]
非常喜欢这个模板，感谢作者！

目前发现有这个问题，可能只要把 ``_includes/snippets/prepend-baseurl.html`` 修改一下就好了。

https://paste.ubuntu.com/26249920/

**Comment by kitian616** [comment]
呃。。。`nav_lists` 确实是不支持的，目前就 `home` 是支持的，见[HERE](https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_includes/blog/header.html#L21)。
之所以没有在 `prepend-baseurl` 加绝对路径的判断是因为会引起其他的问题。
这个问题只需要把那段代码复制 `nav_lists` 循环里即可，晚上编码一把。另外，欢迎提 pr 😄。（果然出现了这种需求...）
