### ISSUE TITLE
Feature request: asm highlight not supported

### ISSUE THREAD

**Issue by agfn** [kitian616/jekyll-TeXt-theme#213]
**Description**

I had tried wrap code block with both `asm` and `x86asm`, but all not worked, however `c` worked fine.

This is the link of issue blog:
https://lavender-tree.github.io/2019/09/09/%E5%8F%8C%E7%B3%BB%E7%BB%9F%E5%BC%95%E5%AF%BC.html

The issue is like this: 

![image](https://user-images.githubusercontent.com/44033552/64549195-ce207480-d362-11e9-8306-da3eb50bae69.png)

My blog is based on gitpage.

**Comment by Lominean** [comment]
Code highlight is not done by theme. Is is done [by Jekyll](https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting), with [Rouge](https://github.com/rouge-ruby/rouge). Try type ```nasm``` instead of ```asm``` as a workaround.
