### ISSUE TITLE
Which files can I delete?

### ISSUE THREAD

**Issue by m415** [kitian616/jekyll-TeXt-theme#229]
I'm a green hand to Jekyll, and I don't konw what files in this repository are necessary to maintain the basic functions of TeXt, but I think some files like  `.travis.yml` , `screenshots` and `.vscode` are not needed for common users. Could you explain which files can we delete if we want a clean or a "minimal" TeXt ? Thanks.

**Comment by kitian616** [comment]
Hi, you can delete all the files and folders below for a minimal TeXt:
.github/
.vscode/
docs/
screenshots/
test/
tools/
.eslintrc
.stylelintignore
.stylelintrc
.travis.yml
CHANGELOG.md
HOW_TO_RELEASE.md
screenshot.jpg
