### ISSUE TITLE
主页的背景图片能否更改？

### ISSUE THREAD

**Issue by xuehongyanL** [kitian616/jekyll-TeXt-theme#23]
如题↑

**Comment by WangQiru** [comment]
背景？这主题是纯色背景，可以自己CSS加

**Comment by xuehongyanL** [comment]
我是说那个全是积木的那个背景

**Comment by WangQiru** [comment]
积木是什么鬼？不是这个主题吧

**Comment by kitian616** [comment]
你指我的网站首页吧，这个页面属于基于主题的自定义页面。背景图片的代码见[代码段](https://github.com/kitian616/kitian616.github.io/blob/master/index.html#L18)。

**Comment by xuehongyanL** [comment]
在一个scss里找到背景的图片了，谢谢

**Comment by kitian616** [comment]
problem solved, close.
