### ISSUE TITLE
Feature request: sidebar without buttons at the bottom of the page

### ISSUE THREAD

**Issue by Gondolav** [kitian616/jekyll-TeXt-theme#232]
## Description

Hi, is there a way to have a sidebar without having the "PREVIOUS" and "NEXT" buttons at the bottom of the page? Thanks a lot for your help, well done for the theme!

**Comment by xmehulx** [comment]
You can just remove or comment those lines. It is present in **_includes/article-section-navigator.html** with the class name **article__section-navigator**

**Comment by Gondolav** [comment]
Thanks!
