### ISSUE TITLE
Bug: comments does not work if you don't have leanCloud(assumption)

### ISSUE THREAD

**Issue by hur-kyuh-leez** [kitian616/jekyll-TeXt-theme#235]
**Description**
I have tried to get comments work using two of my GitHub accounts, but could not get it to work. 
I am assuming it is due to leanCloud since all the other repository with leanClound info, the comments are working, but could not verify 100% since leanCloud requires Chinese mobile number to get an appId.

Attempted to solve the problem by adding a key to each post, since
in /_includes/comments-providers/disqus.html file, I assumed "page.key" might be the issue.
But I failed to make comments provider work.

All jekyll-TeXt-theme website that has figured out how the comments work seems to have leanClound appId.

**Steps to Reproduce**

1. clone via "If you host your site on GitHub Pages, you can just fork jekyll-TeXt-theme, then rename the repository to USERNAME.github.io — replacing USERNAME with your GitHub username."
2. change "comments" in _config.yml

**Expected behavior**
comments provider all not working

**Comment by zouyu4524** [comment]
Hi, if you use gitalk as comment provider, you need to enable issues functionality for the repo that hosts your comments, i.e., `hur-kyuh-leez.github.io` in your case. Click `Settings` of the repo, and it's under `Features`.

**Comment by hur-kyuh-leez** [comment]
> Hi, if you use gitalk as comment provider, you need to enable issues functionality for the repo that hosts your comments, i.e., `hur-kyuh-leez.github.io` in your case. Click `Settings` of the repo, and it's under `Features`.

Thank you @zouyu4524 :)
your wisdom > my 6 hours of work 

![블로그 이사 - 시냅시스 2019-12-28 04-46-37](https://user-images.githubusercontent.com/39143397/71530423-10c78600-292d-11ea-99a7-7212f79110ba.png)
