### ISSUE TITLE
数学公式支持的问题

### ISSUE THREAD

**Issue by Holy-Shine** [kitian616/jekyll-TeXt-theme#24]
关于数学公式，在撰写markdown的时候，用的Katex的渲染，例如
$$h_\theta(x)=g(\theta_0+\theta_1x_1+\theta_2x_2)$$
这个是可以渲染的，但是发布到网站后不能正常显示，想问一下我是不是漏了什么。

**Comment by kitian616** [comment]
要加 mathjax: true 的配置才行，默认是不开启的，见   https://github.com/kitian616/jekyll-TeXt-theme/blob/master/README.md#markdown-头信息增强

**Comment by Holy-Shine** [comment]
@kitian616 嗯嗯谢谢作者。解决了部分问题，行内公式无法渲染，比如$f(x)=x+1$；还有就是单行公式无法独立成行。没用过Mathjax的，一直用的KaTex
能不能使用其他渲染引擎的？

**Comment by kitian616** [comment]
因为用的是 kramdown 转换器，它对公式做了一些处理， 见[kramdonw#mathjax](
https://kramdown.gettalong.org/math_engine/mathjax.html)。
为了打到更好的体验，我的推荐是用 `$$` 来表示数学公式（行内），如果要换行，那就直接在 markdown 把公式换行好了，参考[示例](https://github.com/kitian616/jekyll-TeXt-theme/blob/master/test/_posts/2016-12-12-mathjax.md)。
当然你也可以加上转译字符来 `\$\$` 表示独立行的公式。

**Comment by Holy-Shine** [comment]
@kitian616 那么如何更改渲染引擎呢，是不是只要改一下_config.yml里的条目就行了？

**Comment by kitian616** [comment]
这个改的话就不支持 Github Page 了，就改改文章中的公式格式呗，又不是很麻烦。。

**Comment by Holy-Shine** [comment]
好的感谢作者的耐心解答
