### ISSUE TITLE
Bug maybe: 页面公式加载不出来

### ISSUE THREAD

**Issue by xuestrange** [kitian616/jekyll-TeXt-theme#242]
**Description**

[Description of the bug]
**Screenshots **
[![1ivQQ1.md.png](https://s2.ax1x.com/2020/01/20/1ivQQ1.md.png)](https://imgchr.com/i/1ivQQ1)
[Screenshots to help explain your problem.]

**Environment**

- OS: Windows 10
- Browser: Chrome

**Comment by xuestrange** [comment]
补充：我已经设置 mathjax: true, 问题如上。
这个博客做的真的是非常漂亮，可惜我是个编程小白，不是很懂，文档尽量在看了，这个问题一直无法解决

**Comment by kinglyl** [comment]
我看了你的博客，在我这边公式显示正常

**Comment by kinglyl** [comment]
你博客的 tags 设置有问题， 不是 
```
tags:
    - Category
    - iOS
    - ObjC
---

而应该是

```
tags: tag1 tag2 tag3

**Comment by kinglyl** [comment]
打开 `first blood` 文章后不正常了，但是，你那个 `first blood` 没有加载完，到`and they are` 就没了

**Comment by xuestrange** [comment]
> 打开 `first blood` 文章后不正常了，但是，你那个 `first blood` 没有加载完，到`and they are` 就没了
谢谢解答，这个问题我已经解决了，是前边都不得信息不正确造成的。

**Comment by kinglyl** [comment]
> > 打开 `first blood` 文章后不正常了，但是，你那个 `first blood` 没有加载完，到`and they are` 就没了
> > 谢谢解答，这个问题我已经解决了，是前边头部的信息不正确造成的。

解决了就可以关闭ISSUE了
