### ISSUE TITLE
Bug: Problem with JavaScript libraries

### ISSUE THREAD

**Issue by ravila4** [kitian616/jekyll-TeXt-theme#247]
Several features such as the Archive and Aside links are currently broken.
The error seems to be a bad SSL certificate for  `cdn.bootcss.com.` , which prevents loading jquery and other JS libraries.

**Steps to Reproduce**
1. Try to load the Archive page -> posts do not show.
2. Inspect the network connections

![Screenshot from 2020-02-09 20-25-37](https://user-images.githubusercontent.com/9020496/74114885-8b193600-4b7a-11ea-94d5-08f4ae9fdb71.png)

**Comment by stonecharioteer** [comment]
Was this cleared? I am still not seeing the archive posts.
