### ISSUE TITLE
Feature request: asm highlight is needed

### ISSUE THREAD

**Issue by Kiprey** [kitian616/jekyll-TeXt-theme#252]
## Description

[Description of the feature]
A highlight of asm is urgely needed!!!

**Comment by Lominean** [comment]
Code highlight is not done by theme. Is is done [by Jekyll](https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting), with [Rouge](https://github.com/rouge-ruby/rouge). Try type ```nasm``` instead of ```asm``` as a workaround.

**Comment by Kiprey** [comment]
> Code highlight is not done by theme. Is is done [by Jekyll](https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting), with [Rouge](https://github.com/rouge-ruby/rouge). Try type `nasm` instead of `asm` as a workaround.

Yes, you are right. That works. Thank you.
