### ISSUE TITLE
RSS无法显示

### ISSUE THREAD

**Issue by Holy-Shine** [kitian616/jekyll-TeXt-theme#26]
又来请教作者了...
主页点击RSS会出现，
This XML file does not appear to have any style information associated with it. The document tree is shown below.
请问是什么原因

**Comment by kitian616** [comment]
截个图吧…

**Comment by Holy-Shine** [comment]
![image](https://user-images.githubusercontent.com/14997709/34881522-bce520d6-f7ee-11e7-8c4c-0ee2e0eb52c6.png)

**Comment by kitian616** [comment]
这个是站点的 RSS 地址，把他添加到 RSS 软件就网站就可以订阅了。
当然如果你的浏览器安装了 RSS 插件就可以自动识别了，例如 feedly。
可以看看[这篇文章](http://www.ruanyifeng.com/blog/2006/01/rss.html)

**Comment by Holy-Shine** [comment]
web小白感谢作者菊苣科普
