### ISSUE TITLE
Bug: <img> with end tag

### ISSUE THREAD

**Issue by Lominean** [kitian616/jekyll-TeXt-theme#266]
**Description**

`<img>` tags are not allowed to have end tags.
https://github.com/kitian616/jekyll-TeXt-theme/blob/40a8a8712b89533dd3f88c07a22c04b2d036e36e/_layouts/page.html#L174

**Steps to Reproduce**

n/a

**Expected behavior**

n/a

**Screenshots (If Necessary)**

n/a

**Environment (If Necessary)**

n/a

**Comment by emelejhon13** [comment]
t
