### ISSUE TITLE
不知道是不是bug，关于gitalk

### ISSUE THREAD

**Issue by Holy-Shine** [kitian616/jekyll-TeXt-theme#28]
![image](https://user-images.githubusercontent.com/14997709/34903066-34c47910-f864-11e7-8546-6e90a188aa3f.png)

加入gitalk评论系统后，点击登陆按钮会跳回博客首页，不会弹登陆页面，不知道是不是bug

**Comment by kitian616** [comment]
[gittalk 文档](https://github.com/gitalk/gitalk#usage)
> Note: You must specify the website domain url in the Authorization callback URL field.

。。。你都不看文档吗

**Comment by Holy-Shine** [comment]
我都按照文档做了，申请了Github Application，还把id和secret等关键信息填在_config.yml里了，还差什么步骤吗

**Comment by kitian616** [comment]
Github Application 需要配置 `Homepage UR` 和 `Authorization callback URL`， 网站的主页地址。
估计是这个没填对把。

Settings -> Developer settings -> OAuth Apps

**Comment by Holy-Shine** [comment]
![image](https://user-images.githubusercontent.com/14997709/34905431-49d7cc2e-f893-11e7-8620-06e4b97043b1.png)
BlogComment是我为评论建的仓库，另外两个是我博客的URL，访问都没问题啊，是不是因为我用了二级域名的关系（买了个二级域名指向这个GitHub page的地址

**Comment by kitian616** [comment]
那写成自定义的域名把

**Comment by Holy-Shine** [comment]
homepage 和callback URL都改成自己的二级域名，行了，，哎，小白就是折腾，辛苦作者解答了
