### ISSUE TITLE
建议增加 read more /阅读更多 按钮

### ISSUE THREAD

**Issue by iamleeway** [kitian616/jekyll-TeXt-theme#3]
目前 blog 页面显示部分文章摘要，建议在博文的标签按钮旁边增加一个按钮，这样更方便阅读全文。

**Comment by kitian616** [comment]
emmm. 看起来好想也有些必要。

**Comment by kitian616** [comment]
en, 看起来还是有必要的，放到 `1.2.2` 版本，`1.2.1` 集中在现有的功能改进和 bug 的解决。

[设计参考](https://www.smashingmagazine.com/2009/07/designing-read-more-and-continue-reading-links/)
