### ISSUE TITLE
 change color theme

### ISSUE THREAD

**Issue by willguxy** [kitian616/jekyll-TeXt-theme#30]
Hi. The current way of set color theme is to change the file `_sass/settings/_colors.scss`

I was wondering if it's feasible/better to move this change to for example `_config.yml`. Seems to me that it's more convenient to control it from the config file.

**Comment by willguxy** [comment]
By the way, I'm currently using a `Makefile` to keep my template up-to-date. Happy to share with others

```
DIR ?= $$HOME/workspace/jekyll-TeXt-theme

sync:
	rsync -avP $(DIR)/_data/ _data/ && \
	rsync -avP $(DIR)/_includes/ _includes/ && \
	rsync -avP $(DIR)/_layouts/ _layouts/ && \
	rsync -avP $(DIR)/_sass/ _sass/ && \
	rsync -avP $(DIR)/assets/ assets/
```

then just do `make sync`

**Comment by kitian616** [comment]
cool，I'll think about it.
