### ISSUE TITLE
How can I change the color of url link?

### ISSUE THREAD

**Issue by LeoniusChen** [kitian616/jekyll-TeXt-theme#325]
It's really beautiful of this theme ! When I use url link in the post, it shows red which is too dazzling like the pic below. I want to change this color to blue, which code should be modified ?
![image](https://user-images.githubusercontent.com/45724515/108487217-fb07e380-72d9-11eb-8cc7-86a7e4c0537d.png)

**Comment by zheng-wang** [comment]
I came across the same question. My solution was to change the text_skin property in the _config.yml to be a value other than 'default', like shown at https://tianqi.name/jekyll-TeXt-theme/docs/en/configuration#skin.
