### ISSUE TITLE
建议增加搜索功能

### ISSUE THREAD

**Issue by colingpt** [kitian616/jekyll-TeXt-theme#33]
主题非常漂亮，感谢分享！

建议顶部右侧增加一个搜索栏，以前用[jekyll-jacman/](https://github.com/Simpleyyt/jekyll-jacman)主题，使用了[Simple-Jekyll-Search](https://github.com/christian-fei/Simple-Jekyll-Search)功能，非常方便。

期待添加

**Comment by kitian616** [comment]
cool

**Comment by colingpt** [comment]
还有[码志](https://github.com/mzlogin/mzlogin.github.io)这个项目里的搜索框，尽管不能全文搜索，只搜标题，但做的很漂亮，在下拉框显示搜索结果。

**Comment by WangQiru** [comment]
[码志](http://mazhuang.org/)右边这个 popular repository 其实就是我之前想通过 grid layout https://github.com/kitian616/jekyll-TeXt-theme/issues/13 放在 about page 里的

**Comment by kitian616** [comment]
@QiruWang 考虑到 grid layout 会包含很多的 css 类，而主体代码又完全没有必要用到，所以这个就搁置了。
个人认为用 grid layout 布局右边栏其实不太合适，毕竟 grid layout 的宽度是按照比例分配的，这样在某些视图宽度下 右边栏可能会 过宽 或者 过窄。我更希望固定右边栏的宽度，就像有目录的文章页那样。

**Comment by dspdamon** [comment]
风格很喜欢，期待搜索功能 as well。。。。:)

**Comment by kitian616** [comment]
It's on the way. @dspdamon

**Comment by HenryQW** [comment]
很帅。
1. 有没有可能把搜索栏作为一个图标加到 navigation 里，单击后展开 input ？Eg: https://www.w3schools.com/howto/howto_css_animated_search.asp
2. RSS 应该可以移到 footer 单独作为一个图标来节约位置？

**Comment by kitian616** [comment]
- It is possible, but much complex, since I have to make sure this works well on a pc and a phone.

- The theme is used as a blog (not a document), so I think this is not quite necessary.
