### ISSUE TITLE
Can't modify theme footer(gem package)

### ISSUE THREAD

**Issue by maddovr** [kitian616/jekyll-TeXt-theme#36]
Hello, your theme is very great(is it based on NeXt?), however after installing it as a gem, I find myself unable to modify the theme footer(specifically I want to add a discord link and icon) and I've copied and edited both follow-me.html and _follow-me.scss(in their respective folders) also adding a discord.svg in `_includes/icon/social/discord.svg`. Same goes for the footer which I want to Edit using my own name instead of my nick. What am I doing wrong?

**Comment by maddovr** [comment]
That's also the same with icons(how are the various formats supported btw?), theme continues to use its own `assets` folder instead of jekyll site one.

**Comment by WangQiru** [comment]
Did you add discord in `_config.yml` under author section?

```
author:
  name: potato
    discord:  blah
```

**Comment by kitian616** [comment]
- Did `follow-me.html` and `follow-me.sass` goes well? I don't know what link you are adding. you can modify site's nav bar links by `nav_lists` in  _config.yml.

- Icons however, it 's a little complex. you need change **favicon.ico** in the project root and the images in the **assets/images/logo**.

- The footer use `author.name` in the _config.yml as your name. if you want use your own name, just change it to your own name.

**Comment by maddovr** [comment]
A few updates:
- Tried with a classical theme install(no gem theme), adding discord button works perfectly, I only modified `follow-me.html`, `_follow-me.scss` and `_default.scss`, yet jekyll basically asks for all the `_sass` and `_assets` folders to be copied into the site path, which nullifies the gem advantage.

- Replaced logo.svg, generated all icons with artwork and replaced favicon.ico, but two things happen:
 * Title logo remains unchanged
 * Favicon is extremely small in browser no matter what resolution favicon I put in the root folder. And ofc special favicons(apple touch, msbrowserconfig etc do not work). What step am I missing?

The footer uses the title instead of site.author.name and changing it from gem theme doesn't work for some reason, works flawlessly in normal theme install.

**Comment by maddovr** [comment]
An update:

- Decided to drop the gem-based theme, since it was basically a pain, went with the normal one;
- Got favicons to work, however Microsoft edge doesn't(yet to test android and safari)
- I don't know why, but now I've got a weird space when rendering the posts after each typography sign: https://abload.de/img/2018-03-01-13-05-locavrqr0.png what's causing it?

**Comment by WangQiru** [comment]
That’s the font family issue. The primary font is designed for non-western languages like Chinese and Korean, where all characters are full-width.

Eg, `，` is a full-width comma `,`

**Comment by maddovr** [comment]
Actually in the gem based theme this weird space isn't present, and the same can be said for the demo. I thought it was a renderer(kramdown) error, but no idea where its configuration is.

**Comment by WangQiru** [comment]
I just manually replaced the font family in wherever-it-is.scss

**Comment by kitian616** [comment]
Did Android or Safari also have that space?

**Comment by maddovr** [comment]
Oddly enough, safari for iOS(11.2.6) displays correctly and the same for chrome on iOS. Also works for android 7.0 chrome. However on desktop it doesn't display correctly, Suggestions?

**Comment by WangQiru** [comment]
simply because the system font has proper targeting for apple but not other OS.

https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_sass/common/_variables.scss#L2

And this is what I used to replace it, (GitHub style)
```
-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
```

**Comment by maddovr** [comment]
It works, thank you!

**Comment by willguxy** [comment]
@WangQiru I understand that you mentioned we can change fonts in the `.scss` file. I still have two questions regarding this issue?

- Are there font families that render well on most if not all situations? Maybe it's hard to find something similar but more compatible, so just wondering.

- Additionally, can we make fonts configurable in the `_config.yml`?

**Comment by willguxy** [comment]
And by the way, both latest Chrome on Windows 7 and Chromium (default ppa) on Ubuntu 16.04 have this font issue.

**Comment by kitian616** [comment]
- fonts is a very complex things, quite hard to get a font families that  compatible for all the language, I think the most compatible way is just use the Latin fonts. 

- I don't think it's necessary to make a fonts configurable in the _config.yml, You can just change the font in the _sass/common/_variables.scss.

- I 'll change the fonts in the latter edition.
