### ISSUE TITLE
Use favicons from a generator

### ISSUE THREAD

**Issue by maddovr** [kitian616/jekyll-TeXt-theme#37]
I think this begs a different issue, if I'm wrong then sorry ^^
I think many users actually use things like realfavicongenerator & co. since they export even the strange formats(android manifest.json, browserconfig.xml and safari-pinned-tab.svg), is it possible to do this as well in this theme instead of using the script(which isn't the best when it comes to android and msedge).

**Comment by maddovr** [comment]
Tried put both manifest and browserconfig in the root(manually changing the path) however they do not work.

**Comment by kitian616** [comment]
[realfavicongenerator](https://realfavicongenerator.net/)
cool. I'll try it.

**Comment by maddovr** [comment]
That site in particular, which I used for my favicons with my old hexo website, has a useful report tool to check favicon status. 

i.e: your blog's report https://realfavicongenerator.net/favicon_checker?protocol=https&site=tianqi.name%2F

**Comment by maddovr** [comment]
Is there any news on this? Since I've confirmed that putting icons in the root folder doesn't really work with the theme.

**Comment by kitian616** [comment]
Sorry for a late answer. I just tried it, If you want make it work, you need change the path in _includes/head-icons-rel.html (just replace this to the HTML code from realfavicongenerator.com), You can see TeXt use /assets/images/logo/ as the root path.

**Comment by maddovr** [comment]
Solved, thanks.
