### ISSUE TITLE
Disqus doesn't load

### ISSUE THREAD

**Issue by maddovr** [kitian616/jekyll-TeXt-theme#38]
I correctly uncommented and put my disqus shortname in `_config.yml`, also migrated old comments to the new url, however disqus doesn't even seem to load for me. There is nothing written in the english documentation and I can't seem to troubleshoot the problem away(even went to the comment-disqus.html but I can't understand what page.key refers to. Suggestions?

**Comment by WangQiru** [comment]
In _config.yml:
```
disqus:
  shortname: your_shortname
```

**Comment by maddovr** [comment]
My _config.yml
```
## Comment system (Disqus) ##
disqus:
  shortname: kualiti #the Disqus shortname for the site
```

**Comment by maddovr** [comment]
My post front matter:
```
---
layout: post
title: Dite no a CCCP
date: 02-09-2017 08:40:13
tags:
  - Fansub
  - Codecs
  - mpv
  - libass
  - vsfilter
categories: Rants
comment: true
url: https://www.kualiti.net/rants/2017/09/02/dite-no-a-cccp
key: nocccp
---
```
It still won't load disqus at all(let alone comments)

**Comment by WangQiru** [comment]
Maybe a hail mary but can you try removing `comment: true` ? My site doesn't use disqus (gitalk instead) and I didn't put  `comment: true`  there, it works.

**Comment by maddovr** [comment]
It doesn't work, as expected. One thing I've not said is that I migrated my blog from hexo to jekyll and this two posts I have on my blog were written using hexo(and there were comments which I migrated using disqus tool). However I find it strange that it doesn't even load the widget at all, let alone the comments. I will try creating a new post and see if it loads there.

**Comment by maddovr** [comment]
It works now, had to set `JEKYLL_ENV` to production manually(it defaults to development). Thanks a lot!

**Comment by kitian616** [comment]
Oh yes, I didn't update the document..
