### ISSUE TITLE
Bug: How to key for View count of articles

### ISSUE THREAD

**Issue by Ryze-T** [kitian616/jekyll-TeXt-theme#386]
![image](https://user-images.githubusercontent.com/76553352/158723113-3e49d7a3-980c-4660-9684-18a4604e8392.png)

Where to set the key？？？

**Comment by Real-king-Ph** [comment]
[我的博客](https://real-king-ph.github.io/misc/2022/04/05/Text%E4%B8%BB%E9%A2%98%E4%B8%8B-key%E7%9A%84%E9%87%8D%E8%AE%BE&leancloud%E8%BD%AC%E5%9B%BD%E9%99%85%E7%89%88.html)提供了一种方法，可以借鉴借鉴

**Comment by Real-king-Ph** [comment]
where 的话

在你们每篇 markdown 文件的开头都加上这样的一些语句

```markdown
---
key: this-is_A-KEY
.
.
.
title: Where to set key
---
```

[官方文档](http://jekyllcn.com/docs/frontmatter/)
