### ISSUE TITLE
single quotes are displayed weirdly

### ISSUE THREAD

**Issue by willguxy** [kitian616/jekyll-TeXt-theme#39]
For example
![image](https://user-images.githubusercontent.com/13532689/36921006-a4f63d94-1e30-11e8-93c7-392cc4ff2893.png)

It might be related `全角/半角` when the language is set to `zh`. But I'm really not sure

**Comment by WangQiru** [comment]
See https://github.com/kitian616/jekyll-TeXt-theme/issues/36#issuecomment-369626679
