### ISSUE TITLE
Please consider rename files and restructure folder layouts

### ISSUE THREAD

**Issue by HenryQW** [kitian616/jekyll-TeXt-theme#42]
## Renaming
For instance, files under `_includes/scripts`  should have a different extension name. eg. `all.script` or `all_scripts.html`. 

Since there are nested `{% include %}` tag, the current convention is making files indistinguishable, especially from their functionalities/duties.

![Example](http://share.wangqiru.com/i6OgSF+)

## Restruction 
IMO, `components`, `snippets` and `utils` can be somehow merged

**Comment by kitian616** [comment]
- you mean file name like `home-script.html`

- the components is the components in the content  of the pages. snippets just like liquid function, utils somehow, is the additional and optional components. 

- in fact, I'm considering to rename script file to *.js, therefore I can minify and use babel to compile it.

**Comment by maddovr** [comment]
I would also suggest having pages like `all.html` etc in the `_pages` folder. Should be possible by simply altering the nav_list I think, but can't test right now.
