### ISSUE TITLE
Bug: Is MathJax 2.7.4 obsolete? It does not properly render equations anymore.

### ISSUE THREAD

**Issue by angeloyeo** [kitian616/jekyll-TeXt-theme#421]
**Description**

Hi,

I've been using the template for a long time. However, MathJax started not to work properly. This issue started from a few months ago.

Even in the main homepage(https://tianqi.name/jekyll-TeXt-theme/docs/en/markdown-enhancements) the issue persists.

Please see the screenshot below.

![image](https://user-images.githubusercontent.com/23230116/189805370-b7884b1d-5238-4600-8cd3-2c585f902942.png)

Also, how can I fix this issue in my own [blog repo](https://github.com/angeloyeo/angeloyeo.github.io)? 

Please let me know what I can do further for this issue.

Thanks,
Angelo

**Comment by angeloyeo** [comment]
@kitian616 Can you please give me a help?

**Comment by sekisushai** [comment]
In `_data/variable.yml` is the URL for MathJax and the following seems dead:
[https://cdn.bootcss.com/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML](https://cdn.bootcss.com/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML). 
I've replace it with [https://unpkg.com/mathjax@2.7.4/unpacked/MathJax.js?config=TeX-MML-AM_CHTML](https://unpkg.com/mathjax@2.7.4/unpacked/MathJax.js?config=TeX-MML-AM_CHTML) and it seems to work again.

**Comment by angeloyeo** [comment]
@sekisushai Hi,

Thank you so much. It worked! You saved my blog.

**Comment by angeloyeo** [comment]
The fix does not work again.

**Comment by angeloyeo** [comment]
Hi @sekisushai , can I get a help again? Your solution worked well but today, the equations are not rendered again. 

Do you happen to know any ways to fix it?

**Comment by angeloyeo** [comment]
I fixed it by changing the URL to

https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML
