### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by oliwhi** [kitian616/jekyll-TeXt-theme#422]
The site seems to be down. Any way you can get it back up?

Thanks,
Oli

**Comment by Yanghojun** [comment]
If you already fork this repository before site was downed,
How about restoring all contents in your forked repository?

![image](https://user-images.githubusercontent.com/47071360/191528650-6595bcb8-e8cc-4393-be64-c8de988b2e1c.png)

lol..

**Comment by mincong-h** [comment]
I just encountered the same issue here. Is there any update? 🙏

**Comment by angeloyeo** [comment]
See the website below and close the issue if you think it is resolved.

https://kitian616.github.io/jekyll-TeXt-theme/docs/en/quick-start

**Comment by kitian616** [comment]
emmm, the new url is: https://kitian616.github.io/jekyll-TeXt-theme/
It's been updated  in readme file.
