### ISSUE TITLE
Gem based theme problems

### ISSUE THREAD

**Issue by maddovr** [kitian616/jekyll-TeXt-theme#44]
So I tried once again to use the gem based version of your theme(latest 1.5.0), however it has two big problems which I can't seem to find a solution to(and I don't understand where things went wrong):

* Archive page is broken for some reason (tags are grayed out and remain unfocused). Files that I have changed that could lead to this issue are: `_includes/components/tags.html`(only translated Show All to Italian, shouldn't be an issue); `_data/locale.yml` (added Italian localization); `_data/variables.yml` (changed `lang: it`); `/all.html` (added Italian title).

* TOC is not showing up: I have an article with h3 headers(three #) and toc isn't showing up anymore. I've uncommented the `selectors: 'h1,h2,h3'` in `_config.yml` however it's not working.

Everything works flawlessly with non-gem based theme version 1.4.3.

**Comment by maddovr** [comment]
I resolved the tags problem, it was a wrong indentation in the `sources` option. The TOC problem still remains tho.

**Comment by kitian616** [comment]
sources options? It's a bug ?

**Comment by maddovr** [comment]
No, it was a human error on my part, when I downloaded the new `_config.yml` for some reasons safari broke line breaks and didn't notice this one as well. Sorry about it.
