### ISSUE TITLE
home页面无法显示，

### ISSUE THREAD

**Issue by bingqianglin** [kitian616/jekyll-TeXt-theme#51]
hi, 不好意思麻烦问下，我想使用下你的主题，按照readme,操作之后，在本地是正常的，但是我传到github之后发现home页面无法显示对应的页面，只能在归档里面可以看到。

###bingqianglin.github.io/_posts/2015-01-01-article-with-long-toc.md

```
---
layout: post
title: Test - Article With Long TOC
key: 20150101
tags: Test English
---

Article with long TOC.

<!--more-->

## TeXt Heading

### TeXt Heading

### TeXt Heading

#### TeXt Heading

##### TeXt Heading

###### TeXt Heading
```
文件位于https://github.com/bingqianglin/bingqianglin.github.io

我想问下这个问题可能是什么造成的？还请指教一下，谢谢。

**Comment by bingqianglin** [comment]
文件位于https://github.com/bingqianglin/bingqianglin.github.io

**Comment by kitian616** [comment]
想象不出来，你再加一个试试？

**Comment by kitian616** [comment]
[this](https://whenhm.github.io/)? Seems Ok now.

**Comment by wenmm** [comment]
谢谢，404原因是绑定域名导致的。😄
