### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by yicm** [kitian616/jekyll-TeXt-theme#53]
- 文章分享功能，支持微信，微博，facebook，twitter等
- 文章“回到顶部”功能按钮

个人感觉很实用，希望能够实现。参考博文： [http://liberize.github.io/tech/jekyll-add-back-to-top-button.html](https://yicm.github.io/blog/2018/04/18/Create-a-Local-Project-with-Git.html)

**Comment by kitian616** [comment]
Nice blog.

分享功能一直在考虑加上，不过一直没有开始做。

回到顶部这个有实用意义，毕竟目前要去操作导航栏只有回到顶部（当然个人很少用回到顶部按钮）

大赏插件不错

**Comment by kitian616** [comment]
e9bd7c25751a826e0ed25e935dddeb782b1b6e8b
