### ISSUE TITLE
Google analytics功能失效

### ISSUE THREAD

**Issue by RickJiangOnGitHub** [kitian616/jekyll-TeXt-theme#57]
在Web source code中看不出有analytics的相關code展現於page中
查找了一下代碼 debug不出來，可否幫忙修正一下問題，謝謝！

**Comment by kitian616** [comment]
I don't have your site and code, how can I solve your problem ?

**Comment by RickJiangOnGitHub** [comment]
不好意思，原諒我沒有附上code，因為我只有修改_config.yml的Google analytics ID的部分，其它是沒有修改的

`## Google Analytics ##
 ga_tracking_id: UA-******515-1`

**Comment by kitian616** [comment]
在使用 analytics 之前有一个判断，只有在非 development 的时候才会出现：
```
{%- if jekyll.environment != "development" -%}
   ...
{%- endif -%}
```
这是 demo 站点的编辑脚本：
```
JEKYLL_ENV=production bundle exec jekyll build --config ./_config.demo.yml
```
你看看 `JEKYLL_ENV` 变量的值是否为 development，本地启动默认是 development。

**Comment by RickJiangOnGitHub** [comment]
感謝回覆，我有注意到這個判斷式，但我是直接clone您的git到本地端修改相關_config.yml內容後Push到
GitHub，並指向master branch 做為GitHub，是否有可能是在GitHub Jekyll編譯啟動時造成的bug？
謝謝您

**Comment by kitian616** [comment]
不清楚，线索太少，没法判断。
GitHub 在编译的时候默认会把 `JEKYLL_ENV` 的值设置为 production 的。

**Comment by ZeroneCat** [comment]
遇到了同样的问题，cloudflare上有访问数据，但google analytics两天以来一直是0。之前还能看到访问信息…近期并没有对相关代码进行过修改。

设成了private，所以没有办法提供代码了，只是正好看到了这个issue就回复一下。

**Comment by kitian616** [comment]
@ZeroneCat Strange,  I found your site, and there is an error about googletagmanager. 

Can't visit google analytic for a while. so I can't test ...

**Comment by kitian616** [comment]
Oh, Many thanks @ZeroneCat .😄

**Comment by pkayokay** [comment]
@kitian616 has this been resolved? Not sure if this is supposed to work. I can't read the text above. 😭

**Comment by RickJiangOnGitHub** [comment]
@pkayokay My temporary solution is to move Google analytics script to base.html
