### ISSUE TITLE
把click to read more ... 改为read more

### ISSUE THREAD

**Issue by wenmm** [kitian616/jekyll-TeXt-theme#58]
田，你好！如果我要把click to read more改为read more那我应该在哪里修改呢？谢谢！

**Comment by wenmore** [comment]
还有就是我发现我那篇深度学习博客从文章标题到click to read more中间没有折叠，老长了。https://wenmm.github.io/

**Comment by kitian616** [comment]
@wenmm https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_data/locale.yml#L20

**Comment by kitian616** [comment]
@wenmore 加上 `<!--more-->`, 详见 https://github.com/kitian616/jekyll-TeXt-theme#%E6%91%98%E8%A6%81

**Comment by wenmm** [comment]
谢，
