### ISSUE TITLE
如何控制首页摘要的长度？

### ISSUE THREAD

**Issue by AlanKSH** [kitian616/jekyll-TeXt-theme#6]
- 希望能够增加控制长度的设置，现在有点太多了，这样一打开首页和博客页的差别看不出来
- 每一页左上角的名字按钮按下去仍然是当前页，希望能改成主页，应该和Home的功能一样

**Comment by kitian616** [comment]
想控制长度的话，可以在文章中加上 `<!--more-->`。
其实我最初的想法就是自己来控制摘要的内容，我可以在文章开头写上整个文章的一个大概，这样用户在浏览的时候就能够直观的看到文章的大概内容。
不过确实有像你这种需求存在，下版会考虑增加一个`简要摘要`的配置，此时的摘要更短，并且不带HTML。

第二个应该是个 bug。周末发版时修复。

**Comment by AlanKSH** [comment]
我刚上传新的博客，但是提示`“unable to build page. Please try again later.”`
不知道是什么原因，有人遇到过吗？原本的博客都没问题，加了新的之后就报错了。

**Comment by AlanKSH** [comment]
Update:
过了一晚之后就成功了。不知道原因，我在北美，是否时区有关？有没有对时间的限制？

**Comment by kitian616** [comment]
呃，这种问题之前还真没遇到过，可能是那个时候 GitHub 服务不太稳定吧。
我看了你的博客，看起来 Jekyll 在解析代码段的时候有些问题。建议把 md 代码块语法改成 {% highlight %} 这种样式，参考[#highlighting-code-snippets](https://jekyllrb.com/docs/posts/#highlighting-code-snippets)。
