### ISSUE TITLE
Where can I change post content alignment to "Justify"?

### ISSUE THREAD

**Issue by Zhenye-Na** [kitian616/jekyll-TeXt-theme#60]
Hi Qi,

I really appreciate your work for this jekyll Theme, I like it very much.

Recently I try to write my posts, I find out that the contents alignment is not "justify". Could you kindly tell me which part/file/codes should I change to make post contents align justify?

Currently, I have to use `{: style="text-align: justify"}` at the end of each paragraph to make it happen. It is a really verbose task to add it.

Thanks in advance!

Best regards,
Zhenye Na

**Comment by kitian616** [comment]
Hi Zhenye,

Thank you appreciate the theme. 

You can add it [here](https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_sass/components/_article.content.scss#L30), just add a  `p { text-align: justify }` under the `.m-article-content`

**Comment by Zhenye-Na** [comment]
Hi Qi,

Thanks for point out the solution to this issue. It perfectly solves it!

Thanks a ton! ^_^!
