### ISSUE TITLE
GDPR Compliance?

### ISSUE THREAD

**Issue by maddovr** [kitian616/jekyll-TeXt-theme#62]
On May 25th, GDPR will come into effect and it will require any EU website/organization and non-EU with EU visitors/clients to comply with its specifics(opt-in regarding the use of cookies). While I'm not entirely sure about what this means for the theme(where are cookies used?), it would be nice to see a theme-level compliance to avoid issues on the webmasters.

**Comment by maddovr** [comment]
I don't know where cookies are used in this theme, but I think the first easily solvable issue should be adding an option to Google Analytics to anonymize IPs @kitian616

**Comment by maddovr** [comment]
So in order for a website to be GDPR compliant, aside from merging #63 there isn't really anything which should be done I the project itself. However I have a question(two actually). According to https://cookieconsent.insites.com (which I used for my banner) you need to add the banner before </head> and I did so in the base.html layout, however nothing showed up. What am I doing wrong? Another thing is that GDPR requires cookie opt-ins and the possibility to revoke the consent, which means first load should disable all cookies, the above mentioned website gives a code block [here](https://cookieconsent.insites.com/documentation/disabling-cookies/) but I have no idea where I should put it. Ideas?

**Comment by kitian616** [comment]
Add code like this?
```html
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
</script>
```
If so, maybe  because the `load` event emitted before you use `addEventListener` to bind the function.

**Comment by maddovr** [comment]
Yea I managed to get the banner working, however for callback hook to actually block cookies, I have no clue. Any ideas?

**Comment by kitian616** [comment]
you can just try to remove the addEventListener if you put this code at the bottom of the <body> block, eg:
```html
(function() {
  ...
})();
```

and also, you can use `window.pageLoad` to handle the callback, even the `load` event has been emitted, the callback would still working:
```
window.pageLoad.then(function() {
  ...
});
```
you can see the source [here](https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_includes/scripts/utils.js#L17)

**Comment by maddovr** [comment]
So basically I should put this inside utils.js?
```onInitialise: function (status) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    // enable cookies
  }
  if (type == 'opt-out' && !didConsent) {
    // disable cookies
  }
},
 
onStatusChange: function(status, chosenBefore) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    // enable cookies
  }
  if (type == 'opt-out' && !didConsent) {
    // disable cookies
  }
},
 
onRevokeChoice: function() {
  var type = this.options.type;
  if (type == 'opt-in') {
    // disable cookies
  }
  if (type == 'opt-out') {
    // enable cookies
  }
},```

Like I said I've no clue on this.

**Comment by maddovr** [comment]
Mmm, how do I specify Disqus cookie? The only one that needs prior consent is Disqus if you set IP anonymization in google analytics.

**Comment by kitian616** [comment]
errr.. why you want to specify Disqus cookie,  something to do with the banner?

**Comment by maddovr** [comment]
Well you need to disable Disqus entirely until the users click "Agree" on the banner, and you also need to disable Disqus once again if the users ever revoke their choice. Welcome to EU Laws
