### ISSUE TITLE
主页右上角添加新的页面

### ISSUE THREAD

**Issue by willguxy** [kitian616/jekyll-TeXt-theme#66]
@kitian616 

repo最新的commit好像去掉了`nav_lists`。请问我自己定义的页面如何通过`_config.yml`添加呢？

**Comment by kitian616** [comment]
nav_list 移动到 data/navigation.yml 了，[头部导航栏](https://tianqi.name/jekyll-TeXt-theme/docs/zh/navigation#%E5%A4%B4%E9%83%A8%E5%AF%BC%E8%88%AA%E6%A0%8F)

还有就是 layout 名也有变化：post / page -> article, all -> archive, error-404 -> 404。
