### ISSUE TITLE
home和post的阅读数都显示0 views

### ISSUE THREAD

**Issue by Bakumon** [kitian616/jekyll-TeXt-theme#7]
- 国内网络：home和post的阅读数都显示0 views
- 科学上网：正常显示

**Comment by Bakumon** [comment]
好像是 disqus 加载成功后，才会显示阅读数

**Comment by kitian616** [comment]
好像是 leancoud 服务器不太稳定。
在 2017年11月22日，09:31，食梦兽 <notifications@github.com<mailto:notifications@github.com>> 写道：


好像是 disqus 加载成功后，才会显示阅读数

**Comment by Bakumon** [comment]
**找到原因了，leancloud 的api，国内网访问不了。**

比如：
在你的 [极简主题：TeXt Theme](https://tianqi.name/blog/2017/10/05/TeXt-theme.html) 这篇文章中，这个链接超时
![image](https://user-images.githubusercontent.com/12182189/33108978-f146bddc-cf79-11e7-9867-19dc383162c5.png)

https://api.leancloud.cn/1.1/classes/ThomasBlog?&where=%7B%22key%22%3A%22100017%22%7D&limit=1

就是它，这个链接是访问不了的

看来是 leancloud 的锅，**请教一下，怎么解决这个问题，需要在 leancloud 中配置什么吗？**

**Comment by Bakumon** [comment]
找到了解决方案：
http://blog.csdn.net/XcantloadX/article/details/78301853

**Comment by kitian616** [comment]
这样改的话就不好作为配置提供了，周末把主题所用的 leancloud 更新到最新版。
