### ISSUE TITLE
Old header bar and button style

### ISSUE THREAD

**Issue by maddovr** [kitian616/jekyll-TeXt-theme#70]
With TeXt 2.0.0, header bar is the same color as the background(white) instead of the old gray, buttons are also smaller(and that affect readability for me, in tags at least), toc being also affected from this. What and how should I modify to bring them back like in 1.5.0?

Even spacing between lines seems to have been reduced, and this imho is also a change that negatively impacts readability, so I'd like to know how to revert it.

**Comment by kitian616** [comment]
1. Just add a background-color under `.header` [SEE](https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_sass/components/_header.scss#L1)

2.  Delete `button--sml` class [SEE](https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_includes/article-info.html#L44).

3. Just set [THIS](https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_sass/common/components/_toc.scss#L17) a little bigger.

4. The space between paragraphs(lines) is not changed.

**Comment by maddovr** [comment]
Thank you for your time, however before closing I must say that some spacing(or maybe font-related stuff) has changed in the theme somehwere, I mean [1.5.0](https://www.kualiti.net/) and [2.0.0](https://5b3b9b6a3813f01464f16e2c--kualiti.netlify.com/). Fonts look smaller, tags are closer to the **Read more** button. Site is in italian so you can ignore the language(btw would you like me to contribute italian localization?). Another unrelated thing, is it possible to resize the license image? Because as it is now it's way too small.

**Comment by kitian616** [comment]
In 2.0.0 I have refactor button and horizontal list(tag list). that effect tags button , TOC, footer etc. I just want to emphasize the content In the article info so I use a small size for the tag buttons. I know the license image is too small, this will optimize latter as well as the author profile card.

It would be great if you add a Italian localization. Just add it in *_data/locale.yml* .
