### ISSUE TITLE
Setting `mathjax:true` in test / _config.yml does not take effect?

### ISSUE THREAD

**Issue by xiaohaoliang** [kitian616/jekyll-TeXt-theme#72]
https://github.com/kitian616/jekyll-TeXt-theme/compare/master...xiaohaoliang:test

then 

`[root@szvp000000632 test]# bundle exec jekyll server -H 0.0.0.0 -P 80`  

The math formula in https://github.com/kitian616/jekyll-TeXt-theme/blob/master/test/_posts/2017-07-07-mathjax.md  is missing~    

So ,  please tell me which step I made a mistake ?

**Comment by kitian616** [comment]
Change your settings in the *_config.yml* under your project's **root path**.  /test  folder is a gem-based theme example.

**Comment by kitian616** [comment]
There is a bug, fixed, thx for the issue.

**Comment by jrekier** [comment]
I also have that problem. I installed the theme using the gem method. The math simply won't display. What am I missing ?

the config file:
<img width="350" alt="Screen Shot 2019-07-22 at 21 16 44" src="https://user-images.githubusercontent.com/9407736/61658636-1063f880-acc6-11e9-8cb9-27cf167a4193.png">

front matter:
<img width="573" alt="Screen Shot 2019-07-22 at 21 18 22" src="https://user-images.githubusercontent.com/9407736/61658762-515c0d00-acc6-11e9-91fe-1a05ab00f46d.png">

nothing there:
<img width="1104" alt="Screen Shot 2019-07-22 at 21 16 55" src="https://user-images.githubusercontent.com/9407736/61658769-57ea8480-acc6-11e9-923f-26d3bedd109a.png">

**Comment by kitian616** [comment]
hard to say, Can you provide your page's url ?

**Comment by jrekier** [comment]
I am doing some offline testing. The blog is not online yet. Can this be the reason?
