### ISSUE TITLE
数据公式显示问题

### ISSUE THREAD

**Issue by xiaohaoliang** [kitian616/jekyll-TeXt-theme#73]
```
$ A\in \{ a,d,c \} $       

$ A\in \\{ a,d,c \\} $ 

```   
显示结果  ：
第一个公式， 网页显示花括号 不见, 本地的markdown编辑器(vsCode),有花括号，

第二个公式， 网页显示有花括号，但是和我本地的markdown编辑器(vsCode)显示为换行了

**Comment by kitian616** [comment]
没太研究这个，应该和[这个配置](https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_includes/markdown-enhancements/mathjax.html#L14)有关。

对应的 mathjax 文档在[这里](http://docs.mathjax.org/en/latest/start.html#tex-and-latex-input)

**Comment by xiaohaoliang** [comment]
猜测如下：  
jekyll用的是kramdown引擎的， kramdown支持的数学公式必须用`$$` 来标识， 我这边用了 `$` 来标识，估计那个 花括号前面的`\`就是被kramdown引擎干掉了，然后才轮到 mathjax 做下一步转换。  感觉还是要从kramdown入手， 但是kramdown似乎没提供对应的配置项啊。。。。

mathjax 我在vscode上也用，没这个问题。

**Comment by ManifoldCaffe** [comment]
请问解决了么? 我遇到了同样的问题.
