### ISSUE TITLE
Is there any way to customize logo and favicon with remote_theme?

### ISSUE THREAD

**Issue by turing4ever** [kitian616/jekyll-TeXt-theme#77]
Hi there, 

I am using `remote_theme:kitian616/jekyll-text-theme` for my blog on github. How to customize logo and favicon?

Thanks!

**Comment by turing4ever** [comment]
It would be better if I could keep remote_theme. Any idea?

**Comment by kitian616** [comment]
Maybe you can name own logo file as *logo.svg* and place it under */assets/images/logo* folder to overwrite the default logo. You can overwrite the favicon in the same way if it worked.

**Comment by turing4ever** [comment]
Other than putting the logo.svg under /assets/images/logo/ folder, is there anything else that I need to do? e.g. do I need to change anything in `_config.yml` ?

**Comment by turing4ever** [comment]
Just tried on my local machine: putting a logo.svg under the directory. But the logo on the site is still the old one.

**Comment by maddovr** [comment]
Try putting `logo.svg` inside `_includes/svg/` folder. As for favicons you need to edit and have a custom `head.html` which is also inside the `_includes` folder, you can use realfavicongenerator or anything similar, and specify the path to your images there (although I recommend putting `favicon.ico` and `apple-touch-icon.png` in the root of your website (as some programs use non-HTTP request to get the those two icons and they will always look for them in the root folder), the others are by default in the `assets` folder of your website.

**Comment by turing4ever** [comment]
Thanks for the advice, but I am using remote_theme, so I am not able to modify the source code. I guess what I am looking for is a way to configure those features without modifying the source code.

**Comment by kitian616** [comment]
So have you find out a solution for it? I tried to add another logo file *logo.svg* under * _includes/svg/* path, and it worked.

**Comment by turing4ever** [comment]
Hi @kitian616, the issue is that *_includes/svg/* is not _accessible_ to me when the blog is using _remote_theme_. Because all the folders (including _includes) of the _gem_ is hosted by github using remote_theme. When I clone the github repo of my blog, I can only modify the _config.yml, Gemfile etc, there's no such folder *_includes/svg/*.

**Comment by kitian616** [comment]
I mean [THIS](https://jekyllrb.com/docs/themes/#overriding-theme-defaults). For gem-based themes, you can overwrite the default file by creating a file with the same path in your site's root path. It also works for remote_theme.

You can put your own logo file *logo.svg* under the path*_includes/svg/* in the root path, and it will replace the default *logo.svg* even though the default logo file is hidden in the remote theme.

**Comment by turing4ever** [comment]
Yes, tried your suggestion and it worked. Thank you very much!

**Comment by turing4ever** [comment]
Kitian's solution works and resolved this issue.
