### ISSUE TITLE
Special Character failing builds

### ISSUE THREAD

**Issue by kenman345** [kitian616/jekyll-TeXt-theme#80]
Starts here: https://www.reddit.com/r/Jekyll/comments/8zeyja/why_are_all_jekyll_themes_broken_outside_of_github/e2jgkz5/?context=7

My findings are a few comments down./ I believe that an infinity symbol is causing a user of your theme to have a failure.

**Comment by kitian616** [comment]
Oh, wow. thx for the issue.

I just wonder how it work if you add `@charset "utf-8";` at the top line of *_variables.scss*.

**Comment by kenman345** [comment]
Would appreciate if you could comment on that reddit thread because I’m not
running this at all, just relaying my findings after trying to help someone
out.

Love the theme BTw, may use it in the future now that I know about it.
