### ISSUE TITLE
Fold button in sidebar for categories.

### ISSUE THREAD

**Issue by maddovr** [kitian616/jekyll-TeXt-theme#81]
Since I'm running a translation website, I truly like the sidebar layout for fast browsing. However since there will likely be many things in the sidebar, is it possible to have a fold button there? Even the possibility to scroll only the sidebar (dunno if it's possible right now, can't really test it) would be greatly appreciated.

**Comment by maddovr** [comment]
Also is there anything I'm missing since the red "marker" in the sidebar seems like it's not working from me?

**Comment by kitian616** [comment]
The left sidebar is scrollable.

The red "marker" is obtained by comparing the page url and the url you set in the *navtigation.yml*, Maybe the url of the page and the url you set are not the same.

**Comment by maddovr** [comment]
Great!
Yup it was a typo that caused the absence of the red marker, fixed it now. Would it be possible to have "fold" buttons for category elements?

**Comment by maddovr** [comment]
While I'm at it, I found that the Next/Previous Links at the end of the article are swapped, as can be seen [here](https://5b57ae89e39e7c62fb755d89--kualiti.netlify.com/novels/eroe_realista/volume_1/prologo/). Is there a way to change this behaviour or is there something I'm doing wrong?

**Comment by kitian616** [comment]
it depends on the sort of posts.
For now, TeXt only support sorting by publish data. You can make "Prologo" newer than "Capitolo 1".

**Comment by kitian616** [comment]
Articles whit `sidebar.toc` now support section navigator (previous and next navigator), maybe you can update your theme.
