### ISSUE TITLE
Failed to load tomorrow highlight theme using gem

### ISSUE THREAD

**Issue by maddovr** [kitian616/jekyll-TeXt-theme#83]
When using the gem theme version, jekyll throws out this error 

jekyll 3.8.3 | Error:  File to import not found or unreadable: ./highlight/tomorrow.
Load paths:
  C:/Users/User Pc/Desktop/kualiti-jekyll/_sass
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-text-theme-2.0.2/_sass
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-text-theme-2.0.2/_sass on line 69

It seems highlight folder has permissions problem for some reason (I ensured gems were updated correctly).

Scrubbing on the net I found that it might not be possible to import whole directories using @import, is that the case?

**Comment by kitian616** [comment]
It's OK on my mac, maybe it just broke on Windows?

**Comment by maddovr** [comment]
Cannot test on my mac atm, however I must point thai I have a custom default.scss, merely added two colors. Does it matter? It also fails on ubuntu.

**Comment by maddovr** [comment]
Works now, thanks!
