### ISSUE TITLE
Dependency Error: jekyll-remote-theme is not installed

### ISSUE THREAD

**Issue by ZeroneCat** [kitian616/jekyll-TeXt-theme#85]
I just encountered the dependency error after I cloned this repo and attempted to set it up locally.
```
Dependency Error: Yikes! It looks like you don't have jekyll-remote-theme or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'Could not open library 'libcurl': The specified module could not be found. . Could not open library 'libcurl.dll': The specified module could not be found. . Could not open library 'libcurl.so.4': The specified module could not be found. . Could not open library 'libcurl.so.4.dll': The specified module could not be found. ' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
```

I found this: https://github.com/jekyll/jekyll/issues/6660 however, and fixed the error by changing `github-pages (172)` to `github-pages (170)` in Gemfile.lock.

Just to share this with anybody who have the same problem :).

**Comment by ZeroneCat** [comment]
Another problem: TeXt2.0 still fails to be tracked by google analytics.
Google recommends gtag.js rather than analytics.js, and suggests to put gtag.js as the first item into the <HEAD>. I was thinking of creating a pull request, but I'm not proficient in working with github.

And I strongly recommend [valine](https://github.com/xCss/Valine) as a good choice for comment system: good looking, markdown-friendly, and free from registration and log-in.

**Comment by kitian616** [comment]
@ZeroneCat I think you can put this "Another problem" in a new issue.
