### ISSUE TITLE
navigation doesn't show red underline as in demo site

### ISSUE THREAD

**Issue by babaq** [kitian616/jekyll-TeXt-theme#89]
Hi,
I just begin to use the TeXt theme, but both the header navigation and sidebar navigation showed no underline and color highlight, and user have no idea where the current navigation is.

I double it I may missed some config settings, but failed after experiments changing various parameters in _config.yml.

The site I build is https://vlabsys.github.io

**Comment by babaq** [comment]
according to the issue #81 , the problem solved after adding permalink: `the_url` in the front matter of the pages that matching the exact `the_url` in _data/navigation.yml. 

it would be better to include this tip in the TeXt doc.

**Comment by kitian616** [comment]
The red underline show when the url in* _data/navigation.yml* equals to the page's url, You can specify **a path** by `permalink` key, this will overwrite the **default path**.
